%% ----------------------------------------------------------------------------------------- %%
% Panel VAR with flexible homogeneity restrictions
% ------------------------------------------------------------------------------------------ %%
% Written by Jan Prueser and Boris Blagov
% This version: 05.10.2020
% Changelog:
%
% ------------------------------------------------------------------------------------------ %%
%% HOUSEKEEPING
clear
clc

addpath('functions');
addpath('data');
addpath('MonteCarlo_rev')
% tic
%% SETUP
spec_tab        = readtable('PanelVAR_MC.xlsx','Sheet','setup','ReadRowNames',true);

% load MC_dataset_rev;
% Generate the MC data
Generate_MC_data
load MC_compTime;

for MC_spec = 1:9
    % data_spec_vec
    % 120 and 121 are based on data generated by a flat prior var
    % 130 and 131 are based on data generated by a shrinkage prior var
    % 140 and 141 are based on data generated by 10 countries that are identical
    
    % setup_spec_vec
    % 1-1000 are vars estimated with our pooling and shrinkage prior
    % 1001-2000 are vars estimated with Minnesota prior
    % 2001-3000 are vars estimated with our pooling prior only (no shrinkage)
    % 3001-4000 are vars estimated with a flat prior (no shrinkage)


    switch MC_spec
        case 1
            setup_spec_vec  = [1:1000];  
            data_spec_vec   = [120 121];    % 
        case 2
            setup_spec_vec  = [1:1000];  
            data_spec_vec   = [130 131];    % 
        case 3
            setup_spec_vec  = [1:1000];  
            data_spec_vec   = [140 141];    % 
        case 4
            setup_spec_vec  = [1001:2000];  
            data_spec_vec   = [120 121];    % 
        case 5
            setup_spec_vec  = [1001:2000];  
            data_spec_vec   = [130 131];    % 
        case 6
            setup_spec_vec  = [1001:2000];  
            data_spec_vec   = [140 141];    % 
        case 7
            setup_spec_vec  = [2001:3000];  
            data_spec_vec   = [120 121];    % 
        case 8
            setup_spec_vec  = [2001:3000];  
            data_spec_vec   = [130 131];    % 
        case 9
            setup_spec_vec  = [2001:3000];  
            data_spec_vec   = [140 141];    % 
        case 10
            % for measuring computational time
            setup_spec_vec  = [4001:4002];  %20   % A vector of seutp specifications to estimate, lines from the file PanelVAR_output.xlsx,
            data_spec_vec   = [160:168]; 
    end  







    dataspec_string = strcat(num2str(data_spec_vec(1)),'_',num2str(data_spec_vec(end))); % for naming


    if setup_spec_vec(1)>=01&&setup_spec_vec(end)<=1000
        % %This is HC prior
        % MC_savename = strcat('MC_pVAR_HC',dataspec_string,'_T',num2str(setup_spec_vec(1)),'_T',num2str(setup_spec_vec(end)),'.mat');
        % This is shrinkage and pooling prior
        MC_savename = strcat('MC_pVAR_snp',dataspec_string,'_T',num2str(setup_spec_vec(1)),'_T',num2str(setup_spec_vec(end)),'.mat');

    elseif setup_spec_vec(1)>=1001&&setup_spec_vec(end)<=2000
        % % This is t-prior
        % MC_savename = strcat('MC_pVAR',dataspec_string,'_t_T',num2str(setup_spec_vec(1)),'_T',num2str(setup_spec_vec(end)),'.mat');
        % This is only Minnesota shrinkage
        MC_savename = strcat('MC_VAR_Monly',dataspec_string,'_T',num2str(setup_spec_vec(1)),'_T',num2str(setup_spec_vec(end)),'.mat');
    elseif setup_spec_vec(1)>=2001&&setup_spec_vec(end)<=3000
        % % % This is Minnesota prior
        % % MC_savename = strcat('MC_pVAR',dataspec_string,'_Minn_T',num2str(setup_spec_vec(1)),'_T',num2str(setup_spec_vec(end)),'.mat');

        % This is only pooling
        MC_savename = strcat('MC_pVAR_poo',dataspec_string,'_T',num2str(setup_spec_vec(1)),'_T',num2str(setup_spec_vec(end)),'.mat');

    elseif setup_spec_vec(1)>=3001&&setup_spec_vec(end)<=4000
        %This is flat prior
        MC_savename = strcat('MCpVAR_flat',dataspec_string,'_T',num2str(setup_spec_vec(1)),'_T',num2str(setup_spec_vec(end)),'.mat');
    elseif setup_spec_vec(1)>=4001&&setup_spec_vec(end)<=4001
        % This is to calcualte computation time
        MC_savename = strcat('MC_snp_compTime',dataspec_string,'_T',num2str(setup_spec_vec(1)),'_T',num2str(setup_spec_vec(end)),'.mat');

    else
        disp('MC_savename not defined, make sure you have the correct ranges')
    end

    xlss            = 0;        % Whether to save the output
    n_pseudo        = 0;       % Set to 0 or to 40. Whether to do recursive fcasts
    nps_last        = 0;        % Set to 1 to skip the last estimation or to 0 to estimate with full dataset one last time. Not useful for recursive oos estimation.

    %% ESTIMATION
    if data_spec_vec(1)>=120&&data_spec_vec(end)<=151
        sz = 360; % number of coefficients to store, i.e N*G*G*P 
        sz2 = 1620;% number of var-covar coeff to stoer, i.e. (N*(N-1)/2)*G*G*P   else
    elseif data_spec_vec(1)>=160
        % this is just a placeholder, we don't save them
        sz = 32000; % sz = N*G*G*P for else
        sz2 = 304000; % sz2= 54 (N*(N-1)/2)*G*G*P   else
    end

    n_dataspec          = size(data_spec_vec,2);
    n_setupspec         = size(setup_spec_vec,2);
    beta_AR_mat         = zeros(sz,n_setupspec,n_dataspec);
    beta_AR_prctiles    = zeros(sz,4,n_setupspec);    % we always take 4 percentiles (2.5, 16, 84, 97.5)
    Vbeta_store_mat     = zeros(sz,size(setup_spec_vec,2),size(data_spec_vec,2));
    LambdaCS_comb_MCsave = zeros(sz2,size(setup_spec_vec,2),size(data_spec_vec,2));
    Phi_vec              = zeros(sz,n_dataspec);
    %% -- Outer loop -- %
    % This is the outer loop wher we loop over specification paramters such as lags, priors, etc.
    for mm = 1:n_setupspec
        clear Input fdata_mat
        %% -- Data loop -- %
        % This is the outer loop wher we loop over the data
        tic
        for kk = 1:n_dataspec
            data_spec = data_spec_vec(kk);
            % Cases for the data
            switch data_spec
                 %% REVISION, complete change of MCs
                case 120
                    % Flat prior dgp, T = 80
                    data_spec_str   = 'simvar_flat_T80';
    %                 [fdata_mat,PHI,N,G,~,Phi_alt,P] = simpvardgp14(120);  
                    fdata_mat=MC_dataset_rev.simpvardgp_flat.fdata_3dmat(1:80,:,mm);
                    PHI = MC_dataset_rev.simpvardgp_flat.PHI;
                    G   = MC_dataset_rev.simpvardgp_flat.G;
                    N   = MC_dataset_rev.simpvardgp_flat.N;
                    Phi_alt = MC_dataset_rev.simpvardgp_flat.Phi_alt;
                    P   = MC_dataset_rev.simpvardgp_flat.P;  

                case 121
                    % Flat prior dgp, T = 200
                    data_spec_str   = 'simvar_flat_T200';
    %                 [fdata_mat,PHI,N,G,~,Phi_alt,P] = simpvardgp14(120);  
                    fdata_mat=MC_dataset_rev.simpvardgp_flat.fdata_3dmat(1:200,:,mm);
                    PHI = MC_dataset_rev.simpvardgp_flat.PHI;
                    G   = MC_dataset_rev.simpvardgp_flat.G;
                    N   = MC_dataset_rev.simpvardgp_flat.N;
                    Phi_alt = MC_dataset_rev.simpvardgp_flat.Phi_alt;
                    P   = MC_dataset_rev.simpvardgp_flat.P;   
                case 130
                    %Shrinkage and pooling prior dgp, T = 80
                    data_spec_str   = 'simvar_shrinkpool_T80';
    %                 [fdata_mat,PHI,N,G,~,Phi_alt,P] = simpvardgp14(120);  
                    fdata_mat=MC_dataset_rev.simpvardgp_shrinkpool.fdata_3dmat(1:80,:,mm);
                    PHI = MC_dataset_rev.simpvardgp_shrinkpool.PHI;
                    G   = MC_dataset_rev.simpvardgp_shrinkpool.G;
                    N   = MC_dataset_rev.simpvardgp_shrinkpool.N;
                    Phi_alt = MC_dataset_rev.simpvardgp_shrinkpool.Phi_alt;
                    P   = MC_dataset_rev.simpvardgp_shrinkpool.P;  

                case 131
                    % Shrinkage and pooling prior dgp, T = 200
                    data_spec_str   = 'simvar_shrinkpool_T200';  
                    fdata_mat=MC_dataset_rev.simpvardgp_shrinkpool.fdata_3dmat(1:200,:,mm);
                    PHI = MC_dataset_rev.simpvardgp_shrinkpool.PHI;
                    G   = MC_dataset_rev.simpvardgp_shrinkpool.G;
                    N   = MC_dataset_rev.simpvardgp_shrinkpool.N;
                    Phi_alt = MC_dataset_rev.simpvardgp_shrinkpool.Phi_alt;
                    P   = MC_dataset_rev.simpvardgp_shrinkpool.P;   
                case 140
                    % identical countries dgp, T = 80
                    data_spec_str   = 'simvar_10ident_T80';  
                    fdata_mat=MC_dataset_rev.simpvardgp_10ident.fdata_3dmat(1:80,:,mm);
                    PHI = MC_dataset_rev.simpvardgp_10ident.PHI;
                    G   = MC_dataset_rev.simpvardgp_10ident.G;
                    N   = MC_dataset_rev.simpvardgp_10ident.N;
                    Phi_alt = MC_dataset_rev.simpvardgp_10ident.Phi_alt;
                    P   = MC_dataset_rev.simpvardgp_10ident.P;  

                case 141
                    % identical countries dgp, T = 200
                    data_spec_str   = 'simvar_10ident_T200';
                    fdata_mat=MC_dataset_rev.simpvardgp_10ident.fdata_3dmat(1:200,:,mm);
                    PHI = MC_dataset_rev.simpvardgp_10ident.PHI;
                    G   = MC_dataset_rev.simpvardgp_10ident.G;
                    N   = MC_dataset_rev.simpvardgp_10ident.N;
                    Phi_alt = MC_dataset_rev.simpvardgp_10ident.Phi_alt;
                    P   = MC_dataset_rev.simpvardgp_10ident.P;   
                 case 150
                    % shrinkage only dgp, T = 80
                    data_spec_str   = 'simvar_shrinkonly_T80';  
                    fdata_mat=MC_dataset_rev.simpvardgp_shrinkonly.fdata_3dmat(1:80,:,mm);
                    PHI = MC_dataset_rev.simpvardgp_shrinkonly.PHI;
                    G   = MC_dataset_rev.simpvardgp_shrinkonly.G;
                    N   = MC_dataset_rev.simpvardgp_shrinkonly.N;
                    Phi_alt = MC_dataset_rev.simpvardgp_shrinkonly.Phi_alt;
                    P   = MC_dataset_rev.simpvardgp_shrinkonly.P;  

                case 151
                    % shrinkage only dgp, T = 200
                    data_spec_str   = 'simvar_shrinkonly_T200';
                    fdata_mat=MC_dataset_rev.simpvardgp_shrinkonly.fdata_3dmat(1:200,:,mm);
                    PHI = MC_dataset_rev.simpvardgp_shrinkonly.PHI;
                    G   = MC_dataset_rev.simpvardgp_shrinkonly.G;
                    N   = MC_dataset_rev.simpvardgp_shrinkonly.N;
                    Phi_alt = MC_dataset_rev.simpvardgp_shrinkonly.Phi_alt;
                    P   = MC_dataset_rev.simpvardgp_shrinkonly.P;  
                case 160
                    % Calculate computational time for various N and G
                    G_num = 5;
                    N_num = 5;
                    data_spec_str  = strcat('simvar_compTime_','N',num2str(N_num),'G',num2str(G_num),'_T80');  
                    fdata_mat=MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).fdata_3dmat(1:80,:,mm);
                    PHI = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).PHI;
                    G   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).G;
                    N   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).N;
                    Phi_alt = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).Phi_alt;
    %                 P   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).P;  
                case 161
                    % Calculate computational time for various N and G
                    G_num = 5;
                    N_num = 10;
                    data_spec_str  = strcat('simvar_compTime_','N',num2str(N_num),'G',num2str(G_num),'_T80');  
                    fdata_mat=MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).fdata_3dmat(1:80,:,mm);
                    PHI = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).PHI;
                    G   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).G;
                    N   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).N;
                    Phi_alt = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).Phi_alt;
    %                 P   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).P;  
                case 162
                    % Calculate computational time for various N and G
                    G_num = 5;
                    N_num = 20;
                    data_spec_str  = strcat('simvar_compTime_','N',num2str(N_num),'G',num2str(G_num),'_T80');  
                    fdata_mat=MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).fdata_3dmat(1:80,:,mm);
                    PHI = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).PHI;
                    G   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).G;
                    N   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).N;
                    Phi_alt = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).Phi_alt;
    %                 P   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).P;  
                case 163
                    % Calculate computational time for various N and G
                    G_num = 10;
                    N_num = 5;
                    data_spec_str  = strcat('simvar_compTime_','N',num2str(N_num),'G',num2str(G_num),'_T80');  
                    fdata_mat=MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).fdata_3dmat(1:80,:,mm);
                    PHI = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).PHI;
                    G   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).G;
                    N   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).N;
                    Phi_alt = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).Phi_alt;
    %                 P   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).P;  
                case 164
                    % Calculate computational time for various N and G
                    G_num = 20;
                    N_num = 5;
                    data_spec_str  = strcat('simvar_compTime_','N',num2str(N_num),'G',num2str(G_num),'_T80');  
                    fdata_mat=MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).fdata_3dmat(1:80,:,mm);
                    PHI = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).PHI;
                    G   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).G;
                    N   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).N;
                    Phi_alt = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).Phi_alt;
    %                 P   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).P; 
                case 165
                    % Calculate computational time for various N and G
                    G_num = 10;
                    N_num = 10;
                    data_spec_str  = strcat('simvar_compTime_','N',num2str(N_num),'G',num2str(G_num),'_T80');  
                    fdata_mat=MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).fdata_3dmat(1:80,:,mm);
                    PHI = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).PHI;
                    G   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).G;
                    N   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).N;
                    Phi_alt = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).Phi_alt;
    %                 P   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).P; 
                case 166
                    % Calculate computational time for various N and G
                    G_num = 20;
                    N_num = 10;
                    data_spec_str  = strcat('simvar_compTime_','N',num2str(N_num),'G',num2str(G_num),'_T80');  
                    fdata_mat=MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).fdata_3dmat(1:80,:,mm);
                    PHI = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).PHI;
                    G   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).G;
                    N   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).N;
                    Phi_alt = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).Phi_alt;
    %                 P   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).P;  
                case 167
                    % Calculate computational time for various N and G
                    G_num = 10;
                    N_num = 20;
                    data_spec_str  = strcat('simvar_compTime_','N',num2str(N_num),'G',num2str(G_num),'_T80');  
                    fdata_mat=MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).fdata_3dmat(1:80,:,mm);
                    PHI = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).PHI;
                    G   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).G;
                    N   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).N;
                    Phi_alt = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).Phi_alt;
    %                 P   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).P;  
                case 168
                    % Calculate computational time for various N and G
                    G_num = 20;
                    N_num = 20;
                    data_spec_str  = strcat('simvar_compTime_','N',num2str(N_num),'G',num2str(G_num),'_T80');  
                    fdata_mat=MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).fdata_3dmat(1:80,:,mm);
                    PHI = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).PHI;
                    G   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).G;
                    N   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).N;
                    Phi_alt = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).Phi_alt;
    %                 P   = MC_compTime.(strcat('N',num2str(N_num),'G',num2str(G_num))).P;  
            end  % End cases for the data settings


            if data_spec == 1||data_spec>100
                % This is for the MC cases
                Input.G = G; Input.N = N;
                Input.Vbeta_ind = 0;
                %             Input.P = 2; % will be overwritten from spec_auto
                %             var_list  = {'v1','v2','v3','v4','v5','v6'};
            else
                G         = size(common_vars,2);  % G variabes for each country
                N         = size(countries,2);    % N countries
                Input.G         = G;  Input.N         = N;
                Input.common_vars = common_vars;
                Input.countries = countries;
                var_list        = cell(1,N*G);
                load Country_data_bal_select.mat
                clear fdata_mat
                for ip = 1:N
                    fdata_mat(:, G*(ip-1)+1:G*ip) = Country_data_balanced.(countries{ip}){:,common_vars};
                    for iq = 1:G
                        var_list{1,(ip-1)*(G) + iq}                = strcat(common_vars{1,iq},'_',countries{1,ip});
                    end
                end
            end
            Input.data_spec_str = data_spec_str;

            % Cases for the specification
            setup_spec  = setup_spec_vec(mm);
            spec_auto
            % Misc settings
            Input.dispsim           = 0000;         % How often to display results. 0 supresses output. Low values (e.g. 1) impact performance. Set to 0 for pseudo oos.
            Input.dispinfo          = 0;            % 1 or 0. Whether to show a summary of the settings. Set to 0 for pseudo oos.


            %% -------------------------------------- Inner loop -------------------------------------- %
            % This is the inner loop for pseudo out-of-sample forecasting. Here we take a subset of the data T_s<T_full
            % and extend the data by one time period each iteration. For each run, the specification must be identical
            for ij = 0:n_pseudo-nps_last                             %n_pseudo is defined in spec0x
                Input.Yins = fdata_mat(1:T_short+ij,:);

                if Input.twostep == 0
                    Output      = VARpanel(Input);
                else
                    tic
                    Output      = VARpanel_twostep(Input);
                    time_el = toc;
                    fprintf('Time elapsed for %4.0f draws of N%1.0f, G%1.0f is %5.0f seconds\n',Input.BURNIN + Input.MCMC,N,G,time_el)
                end


                if n_pseudo > 0 && ij == 0
                    %                  pseudo out-of-sample forecast data (hor x N x n_pseudo)
                    fcast_mean_mat      = zeros(Input.hor,Input.N*Input.G,n_pseudo);
                    fcast_med_mat       = zeros(Input.hor,Input.N*Input.G,n_pseudo);
                    Logpredictivelike_cum= NaN(Input.hor,N*G,n_pseudo);%evtl leichter Input.hor zu nehmen als Hor? f�rs speichern und average nehmen?
                    CRPS    = NaN(Input.hor,N*G,n_pseudo);
                    Logpredictivelike    = NaN(Input.hor,N*G,n_pseudo);
                    fprintf('VARpanel function called with the following settings:\n');
                    disp(Input);
                    fprintf('\n');
                    fprintf('Pseudo out-of-sample forecasting\n');
                end     % if we do an esleif here fcast_mean_mat(:,:,1) is zeroes
                if n_pseudo>0 && ij~=n_pseudo
                    fcast_mean_mat(:,:,ij+1)    = Output.yfor_mean;
                    fcast_med_mat(:,:,ij+1)     = Output.yfor_median;
                    Hor                         = min(size(fdata_mat,1)-(T_short+ij),Input.hor);
                    Yout                        = fdata_mat(T_short+ij+1:T_short+ij+Hor,:);

                    for gn=1:G*N
                        for hh=1:Hor
                            Logpredictivelike(hh,gn,ij+1)= log(  ksdensity(reshape(Output.yfor_draws(hh,gn,:),Input.MCMC,1),Yout(hh,gn))  +1e-15);
                            Logpredictivelike_cum(hh,gn,ij+1)=ksdensity(reshape(Output.yfor_draws(hh,gn,:),Input.MCMC,1),Yout(hh,gn),'Function','cdf');
                            idx = randperm(Input.MCMC);%(hh,gn,ij+1)
                            CRPS(hh,gn,ij+1)=mean(abs(reshape(Output.yfor_draws(hh,gn,:),Input.MCMC,1)-Yout(hh,gn)))...
                                -0.5*mean(abs(reshape(Output.yfor_draws(hh,gn,:),Input.MCMC,1)-reshape(Output.yfor_draws(hh,gn,idx),Input.MCMC,1)));
                        end
                    end

                    fprintf('%2.0f/%2.0f in %f mins.\n',ij+1,n_pseudo,(toc/60));
                    %             figure;
                    %             plot([fdata_mat(T_short-n_pseudo:T_short,:); Output.yfor_median]);
                end
            end     % end inner loop
            %  -------------------------------------- Inner loop -------------------------------------- %
            %%
            if n_pseudo ~=0
                oosdata_mat = fdata_mat(T_short+1:end,:);        % Out-of-sample data set (n_pseudo x N)
                FE_mean     = fcast_eval(oosdata_mat,fcast_mean_mat,var_list);
                FE_med      = fcast_eval(oosdata_mat,fcast_med_mat,var_list);
                LP_mean     = fcast_eval(oosdata_mat,Logpredictivelike,var_list);
                CRPS_mean   = fcast_eval(oosdata_mat,CRPS,var_list);
            end

            %% Only for the MC
            if data_spec>=100 && data_spec<160 
                if isfield(Output,'LambdaCS_comb')
                    LambdaCS_comb_MCsave(:,mm,kk) = Output.LambdaCS_comb;
                end
                if mm == n_setupspec
                    Phi_vec(:,kk) = reshape(Phi_alt,N*G*P*G,1);
                end
                beta_AR_mat(:,mm,kk)       = Output.betaAR_store;
                beta_AR_prctiles(:,:,mm,kk)       = Output.betaAR_prctiles;
            end
    %         toc
    %         fprintf('Time for specification %1.0f: %5.1f seconds \n',data_spec_vec(kk),toc);
        end         % end data loop
        disp(setup_spec)
    end         % end outer loop

    %%
    if data_spec == 1
        LambdaCS_comb_MC_mean = reshape(mean(LambdaCS_comb_MCsave,2),18,3);
        LambdaCS_comb_MC_std  = reshape(std(LambdaCS_comb_MCsave,1,2),18,3);
        MC_savename = strcat('MC_',data_spec_str,'.mat');

        if isfield(Output,'LambdaCS_comb')
            save(MC_savename,'Phi_alt','P','G','N','LambdaCS_comb_MC_mean','LambdaCS_comb_MC_std','beta_AR_mat_mean','beta_AR_mat','Vbeta_store_mean','betaAR_prctiles');
        else
            save(MC_savename,'Phi_alt','P','G','N','beta_AR_mat_mean','beta_AR_mat','Vbeta_store_mean','Vbeta_store_mat','betaAR_prctiles');
        end
        disp(data_spec_str);
    elseif data_spec>=100 && data_spec<160 % above 160 is for computational time
        strct_out.P = P; 
        strct_out.N = N;
        strct_out.G = G;
        strct_out.beta_AR_prctiles           = beta_AR_prctiles;
        strct_out.beta_AR_mat           = beta_AR_mat;
        strct_out.Vbeta_store_mat       = Vbeta_store_mat;
        strct_out.LambdaCS_comb_MCsave  = LambdaCS_comb_MCsave;
        strct_out.Phi_vec               = Phi_vec;
        save(strcat('MonteCarlo_rev\',MC_savename),'strct_out');
    end

end     % end global loop

%