clc
clear
close all

addpath('../functions')

xl_save = 1; % set to 1 to save resutls in MC_results.xlsx

% Loading a structure with the fields
% P, N, G: lags, n_countries, n_vars
% beta_AR_mat(54,200,3): vector of 54 parameters estimated on 100 models for 3 specifications

% 120 and 121 are based on data generated by a flat prior var
% 130 and 131 are based on data generated by a shrinkage prior var
% 140 and 141 are based on data generated by 10 countries that are identical

% 1-1000 are vars estimated with our pooling and shrinkage prior
% 1001-2000 are vars estimated with Minnesota prior
% 2001-3000 are vars estimated with our pooling prior only (no shrinkage)
% 3001-4000 are vars estimated with a flat prior (no shrinkage)


% list_cell = cellstr(ls('*.mat'));
    list_cell = {'MC_VAR_Monly120_121_T1001_T2000.mat'...
    'MC_VAR_Monly130_131_T1001_T2000.mat'...
    'MC_VAR_Monly140_141_T1001_T2000.mat'...
    'MC_pVAR_poo120_121_T2001_T3000.mat' ...
    'MC_pVAR_poo130_131_T2001_T3000.mat' ...
    'MC_pVAR_poo140_141_T2001_T3000.mat' ...
    'MC_pVAR_snp120_121_T1_T1000.mat'    ...
    'MC_pVAR_snp130_131_T1_T1000.mat'    ...
    'MC_pVAR_snp140_141_T1_T1000.mat'    }';
% % list_cell = list_cell(4:end-1,:);
% list_cell(strcmp('MC_dataset_rev.mat',list_cell)) = [];
% list_cell(strcmp('MC_dataset_rev_2only.mat',list_cell))= [];
% list_cell(strcmp('DGPcompTime.mat',list_cell)) = [];
% list_cell(strcmp('DGPflat.mat',list_cell))= [];
% list_cell(strcmp('DGPshrink.mat',list_cell))= [];
% list_cell(strcmp('DGPshrinkpool.mat',list_cell))= [];
% list_cell(strcmp('MC_compTime.mat',list_cell))= [];
% list_cell(3)= [];

n_list = numel(list_cell);

% ii = 1;
tab_test = table();
for iK = 1:n_list
    load(list_cell{iK})  % DGP 3
    MC_strct = strct_out;

    [n_coef, nMC, ~] = size(MC_strct.beta_AR_mat(:,:,:));  % in this case we have 54 coefficients (18x3) for 1000 MC draws


    % ii = 1;     % 1 is for T50, 2 is for T120 and 3 is for T500
    for ii = 1:2
        % bias and variance
        theta_true = MC_strct.Phi_vec(:,ii);           % True coefficients for HC MC, T50
        theta_mean_i = MC_strct.beta_AR_mat(:,:,ii);   % n_coef x nMC  example for T50
        theta_mean_MC = mean(theta_mean_i,2);

        % if ii == 1
        %     theta_tab = array2table(theta_true,'VariableNames',list_cell(iK));
        %     subplot(4,3,iK)
        %     bar(theta_true)
        %     title(strcat('Coefficients_',list_cell{iK}))
        %     tab_test = [tab_test theta_tab];
        % end
        %%
        intvl_struct.bias_vec(:,ii) = mean(theta_mean_i-theta_true,2);
        intvl_struct.bias_sq_vec(:,ii) = mean(theta_mean_i-theta_true,2).^2;
        intvl_struct.variance_vec(:,ii) = mean((theta_mean_i-theta_mean_MC).^2,2);
        intvl_struct.bias(:,ii) = mean(mean(theta_mean_i-theta_true,2));
        intvl_struct.bias_sq(:,ii) = mean(mean(theta_mean_i-theta_true,2).^2);
        intvl_struct.variance(:,ii) = mean(mean((theta_mean_i-theta_mean_MC).^2,2));
        intvl_struct.mse_vec(:,ii) = mean((theta_mean_i-theta_true).^2,2);
        intvl_struct.mse(:,ii) = mean(intvl_struct.mse_vec(:,ii));


        % intervals and interval size
        a = squeeze(MC_strct.beta_AR_prctiles(:,2,:,ii));
        b = squeeze(MC_strct.beta_AR_prctiles(:,3,:,ii));


        a_i_b       = zeros(n_coef,nMC);
        b_less_a     = zeros(n_coef,nMC);

        for kk = 1:nMC
            a_i_b(:,kk)     = (theta_true < b(:,kk) & theta_true > a(:,kk));
            b_less_a(:,kk) = b(:,kk)- a(:,kk);
        end

        intvl_struct.a_i_b_vec(:,ii)    = mean(a_i_b,2);
        intvl_struct.a_i_b(1,ii)        = mean(mean(a_i_b,2));
        intvl_struct.b_less_a_vec(:,ii)  = mean(b-a,2);
        intvl_struct.b_less_a(1,ii)      = mean(mean(b-a,2));

    end

    %% bias
    temp_tab = summaryMC_tab(intvl_struct,'bias',tidy_tab_rows(list_cell{iK}(1:end-4)));
    if iK == 1
        bias_tab = temp_tab;
    else
        bias_tab = [bias_tab;temp_tab];
    end
    bias_tab = sortrows(bias_tab,'DGP');

    %% bias squared
    temp_tab = summaryMC_tab(intvl_struct,'bias_sq',tidy_tab_rows(list_cell{iK}(1:end-4)));
    if iK == 1
        bias_sq_tab = temp_tab;
    else
        bias_sq_tab = [bias_sq_tab;temp_tab];
    end
    bias_sq_tab = sortrows(bias_sq_tab,'DGP');

    %% mse2
    temp_tab = summaryMC_tab(intvl_struct,'mse',tidy_tab_rows(list_cell{iK}(1:end-4)));
    if iK == 1
        mse_tab = temp_tab;
    else
        mse_tab = [mse_tab;temp_tab];
    end
    mse_tab = sortrows(mse_tab,'DGP');
    %% variance
    temp_tab = summaryMC_tab(intvl_struct,'variance',tidy_tab_rows(list_cell{iK}(1:end-4)));
    if iK == 1
        variance_tab = temp_tab;
    else
        variance_tab = [variance_tab;temp_tab];
    end
    variance_tab = sortrows(variance_tab,'DGP');

    
    %% true in interval
    temp_tab = summaryMC_tab(intvl_struct,'a_i_b',tidy_tab_rows(list_cell{iK}(1:end-4)));
    if iK == 1
        interval_tab = temp_tab;
    else
        interval_tab = [interval_tab;temp_tab];
    end
    interval_tab = sortrows(interval_tab,'DGP');
    
    
    %% interval size
    temp_tab = summaryMC_tab(intvl_struct,'b_less_a',tidy_tab_rows(list_cell{iK}(1:end-4)));
    if iK == 1
        interval_size_tab = temp_tab;
    else
        interval_size_tab = [interval_size_tab;temp_tab];
    end
    interval_size_tab = sortrows(interval_size_tab,'DGP');

end

%% MSE using bias^2+var
% mse_tab = [bias_tab(:,1:2) array2table(bias_tab{:,3:end}.^2 + variance_tab{:,3:end},'VariableNames',{'mse_T80', 'mse_T200'})];

%% Display
bias_tab
bias_sq_tab
variance_tab
interval_tab
interval_size_tab
mse_tab
% mse2_tab

wide_tab = join(bias_tab,variance_tab);
wide_tab = join(wide_tab,bias_sq_tab);
wide_tab = join(wide_tab,variance_tab);
wide_tab = join(wide_tab,interval_tab);
wide_tab = join(wide_tab,interval_size_tab);
wide_tab = join(wide_tab,mse_tab);

T80_tab = wide_tab(:,{'prior','DGP','bias_T80','bias_sq_T80','variance_T80','a_i_b_T80','b_less_a_T80','mse_T80'});
T200_tab = wide_tab(:,{'prior','DGP','bias_T200','bias_sq_T200','variance_T200','a_i_b_T200','b_less_a_T200','mse_T200'});

%% Write to file
if xl_save
count = 1; table_size =  size(bias_tab,1); %all tables are the same size
writetable(bias_tab,'MC_results.xlsx','WriteRowNames',1,'Range',strcat('A',num2str(count)));

count = count + table_size + 2; table_size =  size(bias_sq_tab,1); %all tables are the same size
writetable(bias_sq_tab,'MC_results.xlsx','WriteRowNames',1,'Range',strcat('A',num2str(count)));

count = count + table_size + 2;
writetable(variance_tab,'MC_results.xlsx','WriteRowNames',1,'Range',strcat('A',num2str(count)));

count = count + table_size + 2;
writetable(interval_tab,'MC_results.xlsx','WriteRowNames',1,'Range',strcat('A',num2str(count)));

count = count + table_size + 2;
writetable(interval_size_tab,'MC_results.xlsx','WriteRowNames',1,'Range',strcat('A',num2str(count)));

count = count + table_size + 2;
writetable(mse_tab,'MC_results.xlsx','WriteRowNames',1,'Range',strcat('A',num2str(count)));
end